server:
  port: 8076

spring:
  application:
    name: "omnexa-backoffice"
  profiles:
    active: "pilot,messages,mails,validation,smtp"
  config:
    import: "configserver:http://localhost:8071/"
  messages:
    basename: backoffice/backoffice-validation-messages