omnexa:
  database:
    url: "jdbc:mysql://localhost:3306/omnexa_merchant?allowPublicKeyRetrieval=true&useSSL=false"
    username: "Digicore"
    password: "Digicore_123"
    driver: "com.mysql.cj.jdbc.Driver"
  security:
    jwtKeyStorePath: "/Users//maximillian//digicore//sofri//configuration//omnexa-config-server//config//keys//keystore.jks"
    jwtKeyStorePassword: "password"
    jwtKeyAlias: "jwtsigning"
    jwtPrivateKeyPassphrase: "password"
    systemKey: "LD8EH2OF34WL9I8A"
    systemDefinedPermissions: "/Users//maximillian//digicore//sofri//configuration//omnexa-projects//configuration//omnexa-config-server//config//permissions//customer//systemPermissions.json"
    corsAllowedOrigins: "*"
    corsAllowedMethods:
      - POST
      - GET
      - PUT
      - DELETE
      - PATCH
      - HEAD
    corsAllowedHeaders:
      - Content-Type
      - Access-Control-Allow-Headers
      - Access-Control-Allow-Origin
      - Access-Control-Expose-Headers
      - Content-Disposition
      - Authorization
      - Access-Control-Allow-Methods
      - X-Requested-With
    corsAllowedExposedHeaders:
      - Content-Disposition
    allowedUrls:
      - /omnexa-backoffice/documentation/**
      - /actuator/**
      - /v1/**
    platform: "BACKOFFICE"
    filteredUrls:
      - /actuator/**
      - /omnexa-merchant/documentation/**
      - /v1/onboarding/**
      - /v1/activation/process/send-bvn-verification-code
      - /v1/activation/process/validate-bvn
      - /v1/activation/process/signatory/retrieve
      - /v1/activation/process/signatory/update
      - /v1/activation/process/preference/retrieve
      - /v1/customer/**
      - /v1/authentication/process/**
    allowedClientUrls:
      - unity.lucid.local:8073
      - lucid.local:8073
    redisHost: localhost
    redisPort: 6379
    skipBvnOtpValidation: true
    skipSmsValidation: true
  feature:
    modules:
      - name: ROLE
        activities:
          - CREATE
          - EDIT
          - DELETE
          - ENABLE
          - DISABLE
      - name: USER
        activities:
          - CREATE
          - EDIT
          - DELETE
          - ENABLE
          - DISABLE
          - ONBOARD
      - name: APPROVAL_RULE
        activities:
          - CREATE
          - EDIT
    logo: ""
    primaryColor: "#5026fb"
    secondaryColor: "#eceeff"
  swagger:
    developmentServerUrl: "http://localhost:8073/omnexa-backoffice/"
  file:
    fileUploadDirectory: "/Users//maximillian//digicore//sofri//"
    minFileUploadSize: 1000
    maxFileUploadSize: 5000000
    s3BucketName: lucid-staging-bucket
    s3AccessKey: test
    s3SecretKey: test
    s3Url: http://localhost:4566
  template:
    account:
      account_template_path: "/Users//maximillian//digicore//sofri//configuration//omnexa-config-server//config//templates//customer//"
      account_statement: "accountStatement"
      receipt: "accountReceipt"
  misc:
    locationsPath: "/Users//maximillian//digicore//sofri//configuration//omnexa-config-server//config//locations//nigeria-states-and-cities.json"
    onboardingPath: "/auth/onboarding/signatory-account?organizationId=%s&email=%s"


  message:
    onboard:
      duplicate: "User with profile {profile} already exists"
      invalid: "Invalid onboarding request"
      not_found: "User with profile {profile} not found"
      required: "Field {profile} is required"
      successful: "Onboarding completed successfully"

    user:
      duplicate: "User {profile} already exists"
      not_found: "User {profile} not found"
