omnexa:
 message:
  user:
   not_found: "{email} does not exist"
   created: "User created successfully"
   duplicate: "{email} already exists"
   bvn_validation_failed: "Bvn validation failed"
   nin_verification_failed: "Nin verification failed"
  role:
    not_found: "{roleName} does not exist"
    created: "Role created successfully"
    duplicate: "{roleName} already exists"
    conflict: "You can't assign a checker and a maker permission under one role"
    invalid: "Invalid role supplied"
    invalid_permissions: "The following permissions are invalid: {permissions}"
  login:
    login_successful: "{user} logged in successfully"
    login_failed: "Invalid login credentials"
    login_denied: "We detected multiple failed attempt on login, check back in {time} minutes or contact support for help."
    login_denied_description: "{user} login attempt failed {time} times"
    inactive: "Account is inactive"
    password_already_used: "Password has already been previously used"
    old_password_wrong: "The old password provided is wrong"
    system_default_password_cant_be_updated: "Default system users password can't be updated"
    password_updated: "{user} reset password successfully"
  audit:
    create: "A create {module} request has been initiated by {user}"
    onboard: "An onboarding {module} request has been initiated by {user}"
    edit: "An edit {module} request has been initiated by {user}"
    delete: "A delete {module} request has been initiated by {user}"
    approve: "A {action} {module} request has been approved by {user}"
    decline: "A {action} {module} request has been declined by {user}"
    enable: "An enable {module} request has been initiated by {user}"
    disable: "A disable {module} request has been initiated by {user}"
    password_updated: "Password updated successfully by {user}"
  email:
    login_successful_subject: "Login successful"
    onboarding_subject: "Onboarding"
    password_reset_successful_subject: "Password Reset Successful"
    account_statement_subject: "Account Statement"
    password_reset_request_subject: "Password Reset Request"
    password_change_request_subject: "Password Change Request"
  client:
    not_found: "Invalid client"
    duplicate: "{name} already exists"
    invalid: "Invalid application id provided"
  approval:
    not_authorized: "You are not authorized to perform this action"
    not_found: "Invalid activity type supplied"
    not_configured: "Workflow not configured"
    level_not_configured: "Approval leg not configured"
    invalid_type: "Invalid approval type"
    already_treated: "User has already approved this request at a previous stage."
  activation:
    not_found: "Invalid organization id supplied"
    required_fields_missing: "Required fields are missing"
    invalid: "The signatories/directors haven't verified their bvn"
    invalid_payload: "The fields are required for activation"
    not_configured: "Account officer not provided"
    assigned_role_required: "Assigned role is required"
    custodian_role_required: "Custodian role is required"
    company_rep_invalid_role: "Company representative must have a initiator role"
    invalid_role: "Invalid role provided"
    invalid_type: "Invalid account type"
  account:
    not_found: "Account not found for this user"
    duplicate: "Account number already exists"
    activation: "Unable to create account at this time"
    organization_id_mismatch: "Organization id does not match provided account"
  profile:
    not_found: "Profile not found"
    activation: "Unable to create profile at this time"
    duplicate: "Profile already exists"
  transaction:
    not_found: "No transactions found"
  limit:
    not_found: "No limit found"
    limit_violation: "You have violated global limit."
    duplicate: "Limit already exists"
  preference:
    not_found: "No preference found"
    duplicate: "Customer preference already exists"
    invalid: "Invalid preference details provided"
  location:
    not_found: "No Location found"
  branch:
    not_found: "No branch found"
    duplicate: "Customer branch already exists"
  device:
    not_found: "Device not found"
    not_configured: "This operation is not allowed for this access channel"
    duplicate: "Device is already registered with a customer"
    invalid: "This device is either yet to be registered or has been disabled from accessing this profile"
  document:
    not_enough: "Document is required"
    not_found: "No document found"
    invalid: "An error occurred while processing the document."
